name: Run cc-snapshot tests

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up python
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install OpenStack client
        run: python -m pip install --upgrade \
          pip python-openstackclient>=3.16.0 more-itertools<6.0.0

      - name: Run provenance tests
        run: ./tests/test_provenance.sh

      - name: Run interface tests
        run: ./tests/test_interface.sh

      - name: Run check_size test
        run: ./tests/test_check_size.sh
