name: Run cc-snapshot tests

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run provenance tests
        run: ./tests/test_provenance.sh
